version: "2"
services:
  web:
    image: webstack/php
    volumes:
      - .:/home
    ports:
      - 8080:80
    links:
      - db
      - redis
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
    ports:
      - "127.0.0.1:3306:3306"
  redis:
    image: redis
